// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPxc_VGHzIuiPTy4m8hpobCs2jKwE-vWM',
    appId: '1:712968422534:web:b3517b8cda2d28f1317d07',
    messagingSenderId: '712968422534',
    projectId: 'psiquiatrias',
    authDomain: 'psiquiatrias.firebaseapp.com',
    storageBucket: 'psiquiatrias.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd6eF17FYrA2mIp8lmsLe2qU0JsFDZtZg',
    appId: '1:712968422534:android:d95dbacd0be94fac317d07',
    messagingSenderId: '712968422534',
    projectId: 'psiquiatrias',
    storageBucket: 'psiquiatrias.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ5GrMeYFCs2jXsactRbvKGrKDZBzv6do',
    appId: '1:712968422534:ios:7b378f180dd634fb317d07',
    messagingSenderId: '712968422534',
    projectId: 'psiquiatrias',
    storageBucket: 'psiquiatrias.appspot.com',
    iosClientId: '712968422534-8a1966n3prpvf2cq7dvupdi7ghj13glv.apps.googleusercontent.com',
    iosBundleId: 'com.example.psiquiatriaSantaClara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ5GrMeYFCs2jXsactRbvKGrKDZBzv6do',
    appId: '1:712968422534:ios:7b378f180dd634fb317d07',
    messagingSenderId: '712968422534',
    projectId: 'psiquiatrias',
    storageBucket: 'psiquiatrias.appspot.com',
    iosClientId: '712968422534-8a1966n3prpvf2cq7dvupdi7ghj13glv.apps.googleusercontent.com',
    iosBundleId: 'com.example.psiquiatriaSantaClara',
  );
}
